import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SearchBox from "../components/search/searchBox";

import SectionCards from "../components/card/section-cards";

import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from "../lib/videos";
import { redirectUser } from "../utils/redirectUser";
import { useState } from "react";


export async function getServerSideProps(context) {
  
  const { userId, token } = await redirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");

  const travelVideos = await getVideos("indie music");

  // const popularVideos = await getPopularVideos("IN");
  const popularVideos = await getPopularVideos();
  const moviesVideos = await getVideos("hollywood movies");

  return {
    props: {
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      moviesVideos,
      watchItAgainVideos,
      // searchVideos
    },
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
  moviesVideos,
  watchItAgainVideos,
}) {

  const [searchVideos, setSearchVideos] = useState([])
  // const searchVideos = await getVideos(searchValue)

  const searchInputChange = async(value)=>{
  try{
    const promise= await fetch('/api/search',{
      method:"POST",
      body:JSON.stringify({
        searchTerm:value
      })
    })

    const result = await promise.json()


    setSearchVideos(result)
  }catch(e){
    console.log(e)
  }
  
  }
  // console.log(onSearchValue);
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar />
        <Banner
          videoId="4zH5iYM4wJo"
          // videoId="spYbknuOqD4"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <SearchBox onSearchValue={searchInputChange}/>
        <div className={styles.sectionWrapper}>

          {searchVideos.length>0&&<SectionCards title="Searched Videos" videos={searchVideos} size="small" />}
          
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
        
        
          <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />

          <SectionCards title="Travel" videos={travelVideos} size="small" /> 
          <SectionCards title="Movies" videos={moviesVideos} size="medium" />
           <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          /> 
           <SectionCards title="Popular" videos={popularVideos} size="small" /> 
        </div>
      </div>
    </div>
  );
}
